name: CI

on:
  pull_request:
  push:
    branches: [async]

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt .
      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Tests
        run: python -m pytest --cov=onvif --cov-report=term-missing --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
